/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author andre
 */
public class PantallaEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form PantallaEstudiante
     */
    public PantallaEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtBuscarEstudiante = new javax.swing.JTextField();
        jBuscarEstudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstEstudiantes = new javax.swing.JList<>();
        jBAgregarEstudiante = new javax.swing.JButton();
        jBCancelarEstudiante = new javax.swing.JButton();
        jBSalirEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ESTUDIANTES");

        jTxtBuscarEstudiante.setBackground(new java.awt.Color(51, 255, 255));
        jTxtBuscarEstudiante.setText("Buscar");
        jTxtBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBuscarEstudianteActionPerformed(evt);
            }
        });

        jBuscarEstudiante.setBackground(new java.awt.Color(51, 255, 51));
        jBuscarEstudiante.setText("Buscar");

        LstEstudiantes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LstEstudiantes.setToolTipText("");
        jScrollPane1.setViewportView(LstEstudiantes);

        jBAgregarEstudiante.setBackground(new java.awt.Color(153, 153, 0));
        jBAgregarEstudiante.setText("Agregar");
        jBAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarEstudianteActionPerformed(evt);
            }
        });

        jBCancelarEstudiante.setBackground(new java.awt.Color(255, 51, 51));
        jBCancelarEstudiante.setText("Cancelar");
        jBCancelarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarEstudianteActionPerformed(evt);
            }
        });

        jBSalirEstudiante.setBackground(new java.awt.Color(255, 102, 255));
        jBSalirEstudiante.setText("Salir");
        jBSalirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtBuscarEstudiante)
                                .addGap(18, 18, 18)
                                .addComponent(jBuscarEstudiante))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBSalirEstudiante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAgregarEstudiante)
                                .addGap(18, 18, 18)
                                .addComponent(jBCancelarEstudiante)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscarEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarEstudiante)
                    .addComponent(jBCancelarEstudiante)
                    .addComponent(jBSalirEstudiante))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBuscarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBuscarEstudianteActionPerformed

    private void jBAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarEstudianteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EditarEstudiante editestudiante=new EditarEstudiante();
        editestudiante.setVisible(true);
    }//GEN-LAST:event_jBAgregarEstudianteActionPerformed

    private void jBCancelarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarEstudianteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PantallaCurso pantcurso=new PantallaCurso();
        pantcurso.setVisible(true);
    }//GEN-LAST:event_jBCancelarEstudianteActionPerformed

    private void jBSalirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirEstudianteActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBSalirEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> LstEstudiantes;
    private javax.swing.JButton jBAgregarEstudiante;
    private javax.swing.JButton jBCancelarEstudiante;
    private javax.swing.JButton jBSalirEstudiante;
    private javax.swing.JButton jBuscarEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtBuscarEstudiante;
    // End of variables declaration//GEN-END:variables
}
